import json
import logging

from fastapi import APIRouter
from app.models.scene import SceneRequest, SceneResponse
from app.services import gemini as gemini_service
from app.services import scene_log
from app.services.scene_log import LOG_DIR

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/scene", tags=["scene"])

# Fallback scene loaded from a previously-generated log.
_FALLBACK_FILE = LOG_DIR / "2026-03-01_00-04-59_build_a_simple_house.json"
MOCK_SCENE = SceneResponse.model_validate(
    json.loads(_FALLBACK_FILE.read_text(encoding="utf-8"))["scene"]
)


@router.post("/generate", response_model=SceneResponse)
async def generate_scene(request: SceneRequest) -> SceneResponse:
    """
    Accepts a plain-text scene description from Unity and returns a structured
    scene JSON generated by Gemini. Falls back to MOCK_SCENE on failure.
    """
    logger.info(f'Scene generation requested — description="{request.description}"')
    try:
        scene = await gemini_service.generate_scene(request.description)
        logger.info("Scene generation complete")
        source = "gemini"
    except Exception:
        logger.warning("Gemini unavailable — returning fallback scene (simple house)")
        scene = MOCK_SCENE
        source = "mock"

    scene_log.save(request.description, scene, source=source)
    return scene
